const { ROLES } = require("./roleConfig");
const ADMIN_ROLE_VALUES = [
  ROLES.SUPERADMIN,
  ROLES.ADMIN,
  ROLES.FRANCHISE_ADMIN,
  ROLES.ECOMMERCE_ADMIN,
  ROLES.MARKETPLACE_ADMIN,
  ROLES.DIGITAL_MARKETING_ADMIN,
  ROLES.TRAINING_ADMIN,
  ROLES.FINANCE_ADMIN,
  ROLES.REGION_DIRECTOR,
  ROLES.STATE_DIRECTOR,
  ROLES.DISTRICT_DIRECTOR,
  ROLES.EXECUTIVE_DIRECTOR,
  ROLES.LAUNCH_DIRECTOR,
  ROLES.DIRECT_CONSULTANT,
  ROLES.OPERATION_VICE_PRESIDENT,
  ROLES.MEMBERSHIP_VERIFICATION_ADMIN,
  ROLES.CUSTOM_ADMIN,
  ROLES.CHAPTER_PRESIDENT,
  ROLES.VICE_PRESIDENT,
  ROLES.SECRETARY,
];

const ADMIN_ROLE_LABELS = {
  [ROLES.SUPERADMIN]: "Super Admin",
  [ROLES.ADMIN]: "Admin",
  [ROLES.FRANCHISE_ADMIN]: "Franchise Admin",
  [ROLES.ECOMMERCE_ADMIN]: "Ecommerce Admin",
  [ROLES.MARKETPLACE_ADMIN]: "Marketplace Admin",
  [ROLES.DIGITAL_MARKETING_ADMIN]: "Digital Marketing Admin",
  [ROLES.TRAINING_ADMIN]: "Training Admin",
  [ROLES.FINANCE_ADMIN]: "Finance Admin",
  [ROLES.REGION_DIRECTOR]: "Region Director",
  [ROLES.STATE_DIRECTOR]: "State Director",
  [ROLES.DISTRICT_DIRECTOR]: "District Director",
  [ROLES.EXECUTIVE_DIRECTOR]: "Executive Director",
  [ROLES.LAUNCH_DIRECTOR]: "Launch Director",
  [ROLES.DIRECT_CONSULTANT]: "Direct Consultant",
  [ROLES.OPERATION_VICE_PRESIDENT]: "Operation Vice President",
  [ROLES.MEMBERSHIP_VERIFICATION_ADMIN]: "Membership Verification Admin",
  [ROLES.CUSTOM_ADMIN]: "Custom Admin",
  [ROLES.CHAPTER_PRESIDENT]: "Chapter President",
  [ROLES.VICE_PRESIDENT]: "Vice President",
  [ROLES.SECRETARY]: "Secretary",
};

const isAdminRole = (role) => ADMIN_ROLE_VALUES.includes(role);

module.exports = { ADMIN_ROLE_VALUES, ADMIN_ROLE_LABELS, isAdminRole };
