const ROLES = Object.freeze({
  SUPERADMIN: "superadmin",
  ADMIN: "admin",
  FRANCHISE_ADMIN: "franchise_admin",
  ECOMMERCE_ADMIN: "ecommerce_admin",
  MARKETPLACE_ADMIN: "marketplace_admin",
  DIGITAL_MARKETING_ADMIN: "digital_marketing_admin",
  TRAINING_ADMIN: "training_admin",
  FINANCE_ADMIN: "finance_admin",
  REGION_DIRECTOR: "region_director",
  STATE_DIRECTOR: "state_director",
  DISTRICT_DIRECTOR: "district_director",
  EXECUTIVE_DIRECTOR: "executive_director",
  LAUNCH_DIRECTOR: "launch_director",
  DIRECT_CONSULTANT: "direct_consultant",
  OPERATION_VICE_PRESIDENT: "operation_vice_president",
  MEMBERSHIP_VERIFICATION_ADMIN: "membership_verification_admin",
  CUSTOM_ADMIN: "custom_admin",
  CHAPTER_PRESIDENT: "chapter_president",
  VICE_PRESIDENT: "vice_president",
  SECRETARY: "secretary",
  CUSTOMER: "customer",
  USER: "user",
  VENDOR: "vendor",
});

const ROLE_ALIASES = Object.freeze({
  chapter_director: ROLES.EXECUTIVE_DIRECTOR,
  user: ROLES.CUSTOMER,
});

const ROLE_LABELS = Object.freeze({
  [ROLES.SUPERADMIN]: "Super Admin",
  [ROLES.ADMIN]: "Admin",
  [ROLES.FRANCHISE_ADMIN]: "Franchise Admin",
  [ROLES.ECOMMERCE_ADMIN]: "Ecommerce Admin",
  [ROLES.MARKETPLACE_ADMIN]: "Marketplace Admin",
  [ROLES.DIGITAL_MARKETING_ADMIN]: "Digital Marketing Admin",
  [ROLES.TRAINING_ADMIN]: "Training Admin",
  [ROLES.FINANCE_ADMIN]: "Finance Admin",
  [ROLES.REGION_DIRECTOR]: "Region Director",
  [ROLES.STATE_DIRECTOR]: "State Director",
  [ROLES.DISTRICT_DIRECTOR]: "District Director",
  [ROLES.EXECUTIVE_DIRECTOR]: "Executive Director",
  [ROLES.LAUNCH_DIRECTOR]: "Launch Director",
  [ROLES.DIRECT_CONSULTANT]: "Direct Consultant",
  [ROLES.OPERATION_VICE_PRESIDENT]: "Operation Vice President",
  [ROLES.MEMBERSHIP_VERIFICATION_ADMIN]: "Membership Verification Admin",
  [ROLES.CUSTOM_ADMIN]: "Custom Admin",
  [ROLES.CHAPTER_PRESIDENT]: "Chapter President",
  [ROLES.VICE_PRESIDENT]: "Vice President",
  [ROLES.SECRETARY]: "Secretary",
  [ROLES.CUSTOMER]: "Customer",
  [ROLES.USER]: "User",
  [ROLES.VENDOR]: "Vendor",
});

const ROLE_ROUTE_PREFIXES = Object.freeze({
  [ROLES.SUPERADMIN]: "/admin",
  [ROLES.ADMIN]: "/admin",
  [ROLES.FRANCHISE_ADMIN]: "/admin",
  [ROLES.ECOMMERCE_ADMIN]: "/admin",
  [ROLES.MARKETPLACE_ADMIN]: "/admin",
  [ROLES.DIGITAL_MARKETING_ADMIN]: "/admin",
  [ROLES.TRAINING_ADMIN]: "/admin",
  [ROLES.FINANCE_ADMIN]: "/admin",
  [ROLES.REGION_DIRECTOR]: "/region-director",
  [ROLES.STATE_DIRECTOR]: "/state-director",
  [ROLES.DISTRICT_DIRECTOR]: "/district-director",
  [ROLES.EXECUTIVE_DIRECTOR]: "/chapter-director",
  [ROLES.LAUNCH_DIRECTOR]: "/launch-director",
  [ROLES.DIRECT_CONSULTANT]: "/direct-consultant",
  [ROLES.OPERATION_VICE_PRESIDENT]: "/admin",
  [ROLES.MEMBERSHIP_VERIFICATION_ADMIN]: "/admin",
  [ROLES.CUSTOM_ADMIN]: "/admin",
  [ROLES.CHAPTER_PRESIDENT]: "/president",
  [ROLES.VICE_PRESIDENT]: "/vice-president",
  [ROLES.SECRETARY]: "/secretary",
  [ROLES.CUSTOMER]: "/member/dashboard",
  [ROLES.USER]: "/member/dashboard",
  [ROLES.VENDOR]: "/member/dashboard",
});

const ROLE_DASHBOARD_PATHS = Object.freeze({
  [ROLES.SUPERADMIN]: "/admin/dashboard",
  [ROLES.ADMIN]: "/admin/dashboard",
  [ROLES.FRANCHISE_ADMIN]: "/admin/dashboard",
  [ROLES.ECOMMERCE_ADMIN]: "/admin/dashboard",
  [ROLES.MARKETPLACE_ADMIN]: "/admin/dashboard",
  [ROLES.DIGITAL_MARKETING_ADMIN]: "/admin/dashboard",
  [ROLES.TRAINING_ADMIN]: "/admin/dashboard",
  [ROLES.FINANCE_ADMIN]: "/admin/dashboard",
  [ROLES.REGION_DIRECTOR]: "/region-director/dashboard",
  [ROLES.STATE_DIRECTOR]: "/state-director/dashboard",
  [ROLES.DISTRICT_DIRECTOR]: "/district-director/dashboard",
  [ROLES.EXECUTIVE_DIRECTOR]: "/chapter-director/dashboard",
  [ROLES.LAUNCH_DIRECTOR]: "/launch-director/dashboard",
  [ROLES.DIRECT_CONSULTANT]: "/direct-consultant/dashboard",
  [ROLES.OPERATION_VICE_PRESIDENT]: "/admin/dashboard",
  [ROLES.MEMBERSHIP_VERIFICATION_ADMIN]: "/admin/dashboard",
  [ROLES.CUSTOM_ADMIN]: "/admin/dashboard",
  [ROLES.CHAPTER_PRESIDENT]: "/president/dashboard",
  [ROLES.VICE_PRESIDENT]: "/vice-president/dashboard",
  [ROLES.SECRETARY]: "/secretary/dashboard",
  [ROLES.CUSTOMER]: "/member/dashboard",
  [ROLES.USER]: "/member/dashboard",
  [ROLES.VENDOR]: "/vendor",
});

const ROLE_ORGANIZATION_LEVEL = Object.freeze({
  [ROLES.SUPERADMIN]: "global",
  [ROLES.ADMIN]: "global",
  [ROLES.FRANCHISE_ADMIN]: "global",
  [ROLES.ECOMMERCE_ADMIN]: "global",
  [ROLES.MARKETPLACE_ADMIN]: "global",
  [ROLES.DIGITAL_MARKETING_ADMIN]: "global",
  [ROLES.TRAINING_ADMIN]: "global",
  [ROLES.FINANCE_ADMIN]: "global",
  [ROLES.REGION_DIRECTOR]: "region",
  [ROLES.STATE_DIRECTOR]: "state",
  [ROLES.DISTRICT_DIRECTOR]: "district",
  [ROLES.EXECUTIVE_DIRECTOR]: "chapter",
  [ROLES.LAUNCH_DIRECTOR]: "chapter",
  [ROLES.DIRECT_CONSULTANT]: "chapter",
  [ROLES.OPERATION_VICE_PRESIDENT]: "global",
  [ROLES.MEMBERSHIP_VERIFICATION_ADMIN]: "global",
  [ROLES.CUSTOM_ADMIN]: "global",
  [ROLES.CHAPTER_PRESIDENT]: "chapter",
  [ROLES.VICE_PRESIDENT]: "chapter",
  [ROLES.SECRETARY]: "chapter",
  [ROLES.CUSTOMER]: "member",
  [ROLES.USER]: "member",
  [ROLES.VENDOR]: "vendor",
});

module.exports = {
  ROLES,
  ROLE_ALIASES,
  ROLE_LABELS,
  ROLE_ROUTE_PREFIXES,
  ROLE_DASHBOARD_PATHS,
  ROLE_ORGANIZATION_LEVEL,
};
